description: |
  These are buttons, which can be cobined with cards, sections and forms.

patterns:
  account-btn:
    title: "Account Button"
    description: |
      This button is used on a form to create your account.
  create-btn:
    title: "Create Button"
    description: |
      This button is used on a form to create your account.
  facebook-btn:
    title: "Facebook Button"
    description: |
      This button is used to sign in using Facebook, and can be used on a form.
  google-signin:
    title: "Google Sign In"
    description: |
      This button is used to sign in using Google, and can be used on a form.
  login-btn:
    title: "Log In"
    description: |
      This button is used to log into your account on the form page.
  buttons:
    title: "Learn More Button"
    description: |
      This button is used on the information cards.
